export let shoes = [
    {   
        name: `Кеды Nike Blazer Mid Suede`,
        type: `gumshoes`,
        gender: `male`,
        imgUrl: `./images/item-1.png`,
        price: 12999,
    },
    {   
        name: `Кроссовки Nike Air Max 270`,
        type: `sneakers`,
        gender: `male`,
        imgUrl: `./images/item-2.png`,
        price: 12999,
    },
    {   
        name: `Кеды Nike Blazer Mid Suede`,
        type: `gumshoes`,
        gender: `male`,
        imgUrl: `./images/item-3.png`,
        price: 8499,
    },
    {   
        name: `Кроссовки Puma X Aka Boku Future Rider`,
        type: `sneakers`,
        gender: `unisex`,
        imgUrl: `./images/item-4.png`,
        price: 8999,
    },
    {   
        name: `Кроссовки Under Armour Curry 8`,
        type: `sneakers`,
        gender: `male`,
        imgUrl: `./images/item-5.png`,
        price: 15199,
    },
    {   
        name: `Кроссовки Nike Kyrie 7`,
        type: `sneakers`,
        gender: `male`,
        imgUrl: `./images/item-6.png`,
        price: 12299,
    },
    {   
        name: `Кроссовки Jordan Air Jordan 11`,
        type: `sneakers`,
        gender: `male`,
        imgUrl: `./images/item-7.png`,
        price: 10799,
    },
    {   
        name: `Кроссовки Nike LeBron XVIII`,
        type: `sneakers`,
        gender: `male`,
        imgUrl: `./images/item-8.png`,
        price: 16499,
    },
    {   
        name: `Кроссовки Nike Lebron XVIII Low`,
        type: `sneakers`,
        gender: `male`,
        imgUrl: `./images/item-9.png`,
        price: 13999,
    },
    {   
        name: `Кеды Nike Blazer Mid Suede`,
        type: `gumshoes`,
        gender: `male`,
        imgUrl: `./images/item-10.png`,
        price: 8499,
    },
    {   
        name: `Кроссовки Puma X Aka Boku Future Rider`,
        type: `sneakers`,
        gender: `male`,
        imgUrl: `./images/item-11.png`,
        price: 8999,
    },
    {   
        name: `Кроссовки Nike Kyrie Flytrap IV`,
        type: `sneakers`,
        gender: `male`,
        imgUrl: `./images/item-12.png`,
        price: 11299,
    },
    {   
        name: `Кеды Converse Chuck Taylor As Core`,
        type: `gumshoes`,
        gender: `unisex`,
        imgUrl: `./images/item-13.png`,
        price: 10399,
    },
    {   
        name: `Кеды Palladium Palla Ace CVS`,
        type: `gumshoes`,
        gender: `male`,
        imgUrl: `./images/item-14.png`,
        price: 9699,
    },
    {   
        name: `Кеды Converse Chuck Taylor All Star Core High Tram`,
        type: `gumshoes`,
        gender: `male`,
        imgUrl: `./images/item-15.png`,
        price: 11399,
    },
    {   
        name: `Кеды Converse Chuck Taylor All Star Seasonal`,
        type: `gumshoes`,
        gender: `unisex`,
        imgUrl: `./images/item-16.png`,
        price: 10399,
    },
    {   
        name: `Кеды Vans Old Skool`,
        type: `gumshoes`,
        gender: `unisex`,
        imgUrl: `./images/item-17.png`,
        price: 8599,
    },
    {   
        name: `Кеды Converse Chuck 70`,
        type: `gumshoes`,
        gender: `unisex`,
        imgUrl: `./images/item-18.png`,
        price: 13499,
    },
    {   
        name: `Кеды Vans Old Skool`,
        type: `gumshoes`,
        gender: `unisex`,
        imgUrl: `./images/item-19.png`,
        price: 8599,
    },
    {   
        name: `Кеды Converse Chuck Taylor All Star Core Trampki`,
        type: `gumshoes`,
        gender: `unisex`,
        imgUrl: `./images/item-20.png`,
        price: 11399,
    },
    {   
        name: `Мужские ботинки Salomon Reveal Chukka Climasalomon™ Waterproof`,
        type: `boots`,
        gender: `male`,
        imgUrl: `./images/item-21.png`,
        price: 16699,
    },
    {   
        name: `Мужские ботинки Salomon X Ultra 4 Mid Winter ClimaSalomon Waterproof`,
        type: `boots`,
        gender: `male`,
        imgUrl: `./images/item-22.png`,
        price: 22799,
    },
    {   
        name: `Ботинки Dr. Martens Vegan 101 6 Eye Boot`,
        type: `boots`,
        gender: `unisex`,
        imgUrl: `./images/item-23.png`,
        price: 23999,
    },
    {   
        name: `Ботинки Dr. Martens 2976 Yellow Stitch Smooth Leather Chelsea Boots`,
        type: `boots`,
        gender: `unisex`,
        imgUrl: `./images/item-24.png`,
        price: 25199,
    },
    {   
        name: `Ботинки Dr. Martens 1460 Pascal Warmwair Valor Waterproof Boots`,
        type: `boots`,
        gender: `unisex`,
        imgUrl: `./images/item-25.png`,
        price: 25199,
    },
    {   
        name: `Ботинки Dr. Martens 1460 Mono`,
        type: `boots`,
        gender: `unisex`,
        imgUrl: `./images/item-26.png`,
        price: 25199,
    },
    {   
        name: `Ботинки Dr. Martens 1460 Nappa`,
        type: `boots`,
        gender: `unisex`,
        imgUrl: `./images/item-27.png`,
        price: 25199,
    },
    {   
        name: `Мужские ботинки Dr. Martens 1460 Pascal`,
        type: `boots`,
        gender: `male`,
        imgUrl: `./images/item-28.png`,
        price: 25199,
    },
    {   
        name: `Мужские ботинки Dr. Martens 1460-8 Eye Boot`,
        type: `boots`,
        gender: `male`,
        imgUrl: `./images/item-29.png`,
        price: 28999,
    },
    {   
        name: `Ботинки Dr. Martens 1460 Smooth`,
        type: `boots`,
        gender: `unisex`,
        imgUrl: `./images/item-30.png`,
        price: 25199,
    },
    {   
        name: `Ботинки Dr. Martens 1460 Smooth Leather`,
        type: `boots`,
        gender: `unisex`,
        imgUrl: `./images/item-31.png`,
        price: 25199,
    },
    {   
        name: `Мужские полусапоги Street Beat Valenkee`,
        type: `boots`,
        gender: `male`,
        imgUrl: `./images/item-32.png`,
        price: 8399,
    },
    {   
        name: `Мужские ботинки Street Beat Habit Boots`,
        type: `boots`,
        gender: `male`,
        imgUrl: `./images/item-33.png`,
        price: 9999,
    },
    {   
        name: `Мужские ботинки Street Beat Habit Boots`,
        type: `boots`,
        gender: `male`,
        imgUrl: `./images/item-34.png`,
        price: 11999,
    },
    {   
        name: `Мужские ботинки Street Beat Wale Boots`,
        type: `boots`,
        gender: `male`,
        imgUrl: `./images/item-35.png`,
        price: 10999,
    },
    {   
        name: `Мужские ботинки Street Beat Wale Boots`,
        type: `boots`,
        gender: `male`,
        imgUrl: `./images/item-36.png`,
        price: 10999,
    },
    {   
        name: `Женские кроссовки Street Beat Rash`,
        type: `sneakers`,
        gender: `female`,
        imgUrl: `./images/item-37.png`,
        price: 8499,
    },
    {   
        name: `Кроссовки Nike Dunk High Lakers`,
        type: `sneakers`,
        gender: `female`,
        imgUrl: `./images/item-38.png`,
        price: 22999,
    },
    {   
        name: `Женские кроссовки Street Beat Wave`,
        type: `sneakers`,
        gender: `female`,
        imgUrl: `./images/item-39.png`,
        price: 6999,
    },
    {   
        name: `Женские кроссовки Street Beat Wave`,
        type: `sneakers`,
        gender: `female`,
        imgUrl: `./images/item-40.png`,
        price: 6999,
    },
    {   
        name: `Кроссовки PUMA RS-Connect Mono`,
        type: `sneakers`,
        gender: `female`,
        imgUrl: `./images/item-42.png`,
        price: 12999,
    },
    {   
        name: `Кроссовки PUMA Prevail`,
        type: `sneakers`,
        gender: `female`,
        imgUrl: `./images/item-43.png`,
        price: 17999,
    },
    {   
        name: `Кеды Converse Chuck Taylor As Core`,
        type: `gumshoes`,
        gender: `female`,
        imgUrl: `./images/item-44.png`,
        price: 10399,
    },
    {   
        name: `Кеды Vans Old Skool`,
        type: `gumshoes`,
        gender: `female`,
        imgUrl: `./images/item-45.png`,
        price: 9199,
    },
    {   
        name: `Кеды Vans Old Skool`,
        type: `gumshoes`,
        gender: `female`,
        imgUrl: `./images/item-46.png`,
        price: 9199,
    },
    {   
        name: `Женские кеды Palladium Palla Ace CVS`,
        type: `gumshoes`,
        gender: `female`,
        imgUrl: `./images/item-47.png`,
        price: 9699,
    },
    {   
        name: `Женские кеды Converse Chuck Taylor All Star Lift Platform Crafted Florals`,
        type: `gumshoes`,
        gender: `female`,
        imgUrl: `./images/item-48.png`,
        price: 9699,
    },
    {   
        name: `Женские кроссовки Street Beat Wave`,
        type: `sneakers`,
        gender: `female`,
        imgUrl: `./images/item-41.png`,
        price: 6999,
    },
];


